### ISSUE TITLE
Pyrit 

### ISSUE THREAD

**Issue by Edyyed** [hacker3983/pyrit-installer#10]
On kali linux

**Comment by hacker3983** [comment]
@Edyyed what is the issue?

**Comment by Edyyed** [comment]
> @hacker3983
Does it work on Kali Linux 2019.4 ?
(Sorry for my bad English I'm Iranian)

**Comment by hacker3983** [comment]
Yes it does it doesn't only work on kali linux it works on other distributions on well!

**Comment by hacker3983** [comment]
i will rename the repository lol to pyrit installer

**Comment by Edyyed** [comment]
> Yes it does it doesn't only work on kali linux it works on other distributions as well!

Oh!! That's Good thanks

**Comment by hacker3983** [comment]
No problem your welcome!

**Comment by Edyyed** [comment]
> i will rename the repository lol to pyrit installer

OK.
