### ISSUE TITLE
I cant install successfully psycopg2 and scapy..

### ISSUE THREAD

**Issue by kkl90** [hacker3983/pyrit-installer#15]
I use command "sudo pip2 install psycopg2":

Collecting psycopg2
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8pGeSd/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8pGeSd/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5oQW1N
         cwd: /tmp/pip-install-8pGeSd/psycopg2/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

for scapy: i use "sudo pip2 install scapy":
Collecting scapy
  Using cached scapy-2.4.5.tar.gz (1.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d_mmEa/scapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d_mmEa/scapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-GgZ6jv
         cwd: /tmp/pip-install-d_mmEa/scapy/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by hacker3983** [comment]
try doing `sudo apt-get install python-setuptools` in your terminal

**Comment by kkl90** [comment]
Yes thanks, I installed scapy, but still can't install psycopg2 with this
big error:
PS: It says that I need to install "psycopg2-binary". I was installed, but
still have the same error..

Collecting psycopg2
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'/tmp/pip-install-bq1CyU/psycopg2/setup.py'"'"';
__file__='"'"'/tmp/pip-install-bq1CyU/psycopg2/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-Dyw54R
       cwd: /tmp/pip-install-bq1CyU/psycopg2/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/psycopg2
  copying lib/tz.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/compat.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/errorcodes.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/_ipaddress.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/sql.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/_lru_cache.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/errors.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/extras.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/__init__.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/extensions.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/_json.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/pool.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/_range.py -> build/lib.linux-x86_64-2.7/psycopg2
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/psycopg
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time
-D_FORTIFY_SOURCE=2 -g
-ffile-prefix-map=/build/python2.7-tNuRkW/python2.7-2.7.18=.
-fstack-protector-strong -Wformat -Werror=format-security -fPIC
-DPSYCOPG_VERSION=2.8.6 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=140002
-DHAVE_LO64=1 -I/usr/include/python2.7 -I. -I/usr/include/postgresql
-I/usr/include/postgresql/14/server -c psycopg/psycopgmodule.c -o
build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o
-Wdeclaration-after-statement
  In file included from psycopg/psycopgmodule.c:28:
  ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or
directory

     36 | #include <libpq-fe.h>


        |          ^~~~~~~~~~~~


  compilation terminated.





  It appears you are missing some prerequisite to build the package from
source.




  You may install a binary package by installing 'psycopg2-binary' from
PyPI.

  If you want to install psycopg2 from source, please install the packages


  required for the build and try again.





  For further information please check the 'doc/src/install.rst' file (also
at

  <https://www.psycopg.org/docs/install.html>).





  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


  ----------------------------------------


  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
Installing collected packages: psycopg2
    Running setup.py install for psycopg2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'/tmp/pip-install-bq1CyU/psycopg2/setup.py'"'"';
__file__='"'"'/tmp/pip-install-bq1CyU/psycopg2/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-RW1Hq8/install-record.txt
--single-version-externally-managed --compile --install-headers
/usr/local/include/python2.7/psycopg2
         cwd: /tmp/pip-install-bq1CyU/psycopg2/


    Complete output (40 lines):


    running install


    running build


    running build_py


    creating build


    creating build/lib.linux-x86_64-2.7


    creating build/lib.linux-x86_64-2.7/psycopg2


    copying lib/tz.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/compat.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/errorcodes.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/_ipaddress.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/sql.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/_lru_cache.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/errors.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/extras.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/__init__.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/extensions.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/_json.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/pool.py -> build/lib.linux-x86_64-2.7/psycopg2


    copying lib/_range.py -> build/lib.linux-x86_64-2.7/psycopg2


    running build_ext


    building 'psycopg2._psycopg' extension


    creating build/temp.linux-x86_64-2.7


    creating build/temp.linux-x86_64-2.7/psycopg


    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time
-D_FORTIFY_SOURCE=2 -g
-ffile-prefix-map=/build/python2.7-tNuRkW/python2.7-2.7.18=.
-fstack-protector-strong -Wformat -Werror=format-security -fPIC
-DPSYCOPG_VERSION=2.8.6 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=140002
-DHAVE_LO64=1 -I/usr/include/python2.7 -I. -I/usr/include/postgresql
-I/usr/include/postgresql/14/server -c psycopg/psycopgmodule.c -o
build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o
-Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:28:


    ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or
directory

       36 | #include <libpq-fe.h>


          |          ^~~~~~~~~~~~


    compilation terminated.





    It appears you are missing some prerequisite to build the package from
source.




    You may install a binary package by installing 'psycopg2-binary' from
PyPI.

    If you want to install psycopg2 from source, please install the
packages

    required for the build and try again.





    For further information please check the 'doc/src/install.rst' file
(also at

    <https://www.psycopg.org/docs/install.html>).





    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


    ----------------------------------------


ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-bq1CyU/psycopg2/setup.py'"'"';
__file__='"'"'/tmp/pip-install-bq1CyU/psycopg2/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-RW1Hq8/install-record.txt
--single-version-externally-managed --compile --install-headers
/usr/local/include/python2.7/psycopg2 Check the logs for full command
output.

чт, 28 апр. 2022 г. в 22:01, hacker3983 ***@***.***>:

**Comment by hacker3983** [comment]
ok np try doing this `sudo apt install libpq-dev python3-dev` then reinstall psycopg2

**Comment by kkl90** [comment]
> ok np try doing this `sudo apt install libpq-dev` then reinstalling psycopg2

Finally its works. Thanks so much for help!

**Comment by hacker3983** [comment]
@kkl90 Also thank you for reporting the issue i could add those commands to the script so that if anyone else experiences those issues i could use that to solve there problem
